### PR TITLE
Opus links

### PR DESCRIPTION
**Pull request by clintonlunn**
- Add opus data to json file in ./docs/opus_data/fl_ngs.json where we pull data from to add to ngs points that also contain opus data. 

- Add google street view link to ngs points

### CODE REVIEW

**Comment by PhilipGriffith** [comment]
Looks good! Is there some reason for keeping the commented-out old `opusData` function?

**Comment by clintonlunn** [comment]
I figured this may be a temporary solution since this data is supposed to be updated regularly (according to the opus map website). If we could build this data periodically with the node script that I sent over and drop it in freac’s server, it would be easier to fetch and ensure what’s on the map is the most up to date data.

**Comment by clintonlunn** [comment]
Or if that proxy server is set up that can avoid CORS, this whole process would be skipped in favor of just fetching from the original source.

**Comment by PhilipGriffith** [comment]
Gotcha. Updates to ArcGIS Server have caused all sorts of havoc, so I'll ask Aron about setting up that proxy script in a day or two. Honestly, I think the proxy is the best way forward, as it will eliminate the need for us to periodically gather and permanently store data on our server that already exists in a public and updated form somewhere else!

**Comment by clintonlunn** [comment]
I hope all works out!

**Comment by PhilipGriffith** [comment]
Me too. :)

**Pull request merged**
