### PR TITLE
Lyr and symbology hotfixes

### PR DESCRIPTION
**Pull request by clintonlunn**
change symbology of counties layer and remove ccr with images layer

### CODE REVIEW

**Comment by clintonlunn** [comment]
No these can be removed.

**Comment by clintonlunn** [comment]
How are these changes looking? 

@PhilipGriffith I read your email about the streetview functionality yesterday. I agree that it may not be the most useful in most situations, but I feel like the user may have a sense of whether a link would bring them to a roadway or not. I would say one advantage of a streetview would be the user could see the closest streetview location nearest to their target point.

**Comment by PhilipGriffith** [comment]
Looking good so far! What are the commented code sections (53-60, 108-120, 128-129, 206, 219) in the infopanel.js file doing?

**Comment by clintonlunn** [comment]
Thanks for pointing those out. I think I had removed the first block of code already, but maybe when either you or I did a pull from master, it was accidentally re-added. For 108-120 those were the dep forms, that contained the potentially bad mhw now measurements, but I don't think we are using them anymore. I'm assuming that also won't change in the future. 

The remaining is just junk, I'll get it out tonight after work. 

Any other discussion on the street view?

**Comment by PhilipGriffith** [comment]
Not yet.

**Pull request merged**
