### PR TITLE
#188/bookmarks

### PR DESCRIPTION
**Pull request by clintonlunn**

### CODE REVIEW

**Comment by clintonlunn** [comment]
This should be at 90% functionality. This is a new bookmarks widget that is positioned where the Legend and LayerList widgets go (bottom left corner of map UI). This works as expected except for one issue I've identified: 
* LocalStorage does not update when a bookmark is renamed. This is is still a WIP.

**Comment by clintonlunn** [comment]
localStorage issues should be accounted for now

**Comment by clintonlunn** [comment]
@shodge17 have you had a chance to look at this? is there anything you have found to not work correctly?

**Comment by shodge17** [comment]
Clinton -- I have not been able to review this yet and will not be able to until tomorrow.  Thanks for the reminder.

**Pull request merged**
