### PR TITLE
Work in Progress: Version upgrade 4.15

### PR DESCRIPTION
**Pull request by clintonlunn**
WORK IN PROGRESS, DO NOT MERGE YET

This branch is focused on upgrading to the latest ArcGIS JavaScript API (actually 4.15 at the time of this writing) as well as fixing some small bugs that are pending along the way. 

Tested so far: 
- Data Query Panel
- Zoom to Feature Panel

Broken: 
Search bar

I know this isn't ready to merge yet, but I want to get some eyes on it for testing and code review.

### CODE REVIEW

**Comment by clintonlunn** [comment]
I think I've screwed up the way that these information panels are being built. I think it also has to do with the opus data. If you watch your network tab when the queries are filling the information panel on the NGS points, you will see that the opus data requests are the bottleneck for everything. I think this could be a contributing factor to the problem. 

As a workaround, maybe we should stop all requests when we initiate another search using the data query tool.

**Comment by PhilipGriffith** [comment]
You're right: in fact, the OPUS data codei s also the root cause of the NaN problem we were seeing earlier. Moreover, because it was asynchronous, you could click on another point, but the information panel would continue to fill up with data that hadn't yet been loaded!

And I agree with you: I think that, as a matter of course, a data query shoud be aborted if another valid data query is initiated.

**Comment by clintonlunn** [comment]
Figured out why search widget isn't working. There was a breaking change in one of the API releases that altered how sources are defined in a search widget. More info in the "sources" property in the [documentation](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Search-SearchViewModel.html#suggestionsEnabled) and here's a reference to a [community post](https://community.esri.com/message/856902-search-widget-not-working) about it. 

After that, I think we're pretty close.

**Comment by clintonlunn** [comment]
@PhilipGriffith 
> And I agree with you: I think that, as a matter of course, a data query shoud be aborted if another valid data query is initiated.

Next thing to fix.

**Comment by PhilipGriffith** [comment]
I'm going to close this request, as I've gone ahead and added your code to a new branch off of master, as there were simply too many merge conflicts between this branch and the latest master branch to feasibly debug. There are still some issues, but they're not related to the upgrade (the change in how search sources are labelled definitely was), so we can simply deal with them moving forward.

**Pull request closed without merging**
