### PR TITLE
Toggle google streetview

### PR DESCRIPTION
**Pull request by clintonlunn**
Added:

- A button at the top of the map that toggles google street view. 
    - When toggled on, identify is disabled and instead a new streetview tab opens on a map click
    - Button must be toggled off to re-enable identify. 

Please let me know what you all think of this functionality. I just opened this PR to start the conversation of changes necessary :-)

### CODE REVIEW

**Comment by shodge17** [comment]
WHat you did has made me think about another possible way to work the street map thing.  I suspect you have the xy coordinate the user identified inside of the information panel that pops up during an identify.  Could you put the street map link inside that info panel?

**Comment by clintonlunn** [comment]
do you mean put the location of the identify click at the top of the info panel? Or put a street view link for each feature that is being identified?

**Comment by shodge17** [comment]
One streetview link at the top of the info panel

**Comment by clintonlunn** [comment]
Sure, I like that idea too. I’ll get that done.

**Comment by shodge17** [comment]
Because many things that people click on will be in the middle of nowhere, many of the streetview links will result in just a black screen.  (find a black section corner in any rural area no close to a road and you will see what I mean.  You will need to write a sentence or 2 about this condition.

**Comment by clintonlunn** [comment]
Right that is definitely a downside to enabling the street view anywhere. I’ll insert a note at the info panel level.

**Comment by clintonlunn** [comment]
@shodge17 @PhilipGriffith  made some changes that I think would satisfy the changes

**Comment by shodge17** [comment]
I like what you have now.  I say take the street view off of the NGS points and I think we will be ready to go.

**Comment by shodge17** [comment]
Clinton
I have not had a chance to review this yet.  In the mean time, I dont like the way the map recenters on the quad or township when you just randomly click in the middle of nowhere.  I am ok with re-centering on points if that is where you click and it finds something.  If it proves difficult to conditionally re-center the map, then lets never re-center.

**Comment by shodge17** [comment]
Hit the wrong button....

**Comment by clintonlunn** [comment]
I just looked through the code, is is a pretty easy change to conditionally zoom/pan or not. I just need to know the specific scenarios that we would wan to zoom/pan and when we don't.

It makes sense that we don't want to pan out of the area when we are zoomed in far enough that we no longer see the area that we originally clicked on. I am wondering if I can conditionally zoom to the center of a polygon only when the point that we originally clicked won't leave the screen view. 

Are there specific scenarios where we would want to zoom? 

Last, should we make a separate branch and pull request for that functionality, or would you like me to combine it into this PR?

**Comment by shodge17** [comment]
Just put everything in this one branch.  things are not too complicated and I know we are going to accept all of this work shortly.

For now, I say we only zoom if the user click on a point record of some kind.  Dont care if it is a CCR, NGS, MHW, etc -- whatever, then zoom ELSE dont zoom

**Comment by clintonlunn** [comment]
Okay, can do. I’ll get that in today.

**Comment by clintonlunn** [comment]
I left zooming capabilities for polylines and points. Zooming for polylines is a little bit clunky, maybe some modification should be done to those in this branch too.

**Comment by PhilipGriffith** [comment]
Hi Clinton!
What's the story with the `identify-zoom-refactor` branch? After this pull request it's now one commit behind `master`. Can it simply be deleted at this point? Or is there some existing code in that branch that still needs to be merged into `master`?
Thanks!

**Comment by clintonlunn** [comment]
Sorry I forgot to delete it last night. I had separated the zoom functionality into a separate branch before Stephen had replied, but merged it back into the street view branch when he said to combine all into one PR.

**Comment by PhilipGriffith** [comment]
Sounds good. I'll just go ahead and delete it, then.

**Pull request merged**
