### PR TITLE
Add High Resolution Imagery and Township-Range-Section links

### PR DESCRIPTION
**Pull request by clintonlunn**
Issue #66. 

**Add to High Resolution Imagery layers:**

- Add General Land Office (GLO) notes (link)
- High-resolution images (link)
- Connect to information panel

**Add to Township-Range-Section layers**

- Add DEP Oculus Database links
- Connect to information panel

I do not have access to the DEP Oculus Database, so I do not think I am able to confirm whether the links work or not, but the links do match for tested locations.

### CODE REVIEW

**Comment by shodge17** [comment]
I must not have the email notifications turned on.  I will look into that.
1) can you add a blue township label like T01N R01E
2) I think we need to either take the quad out of the query or figure out how to NOT zoom to its extents.  It is too distracting when it zooms way out like it does currently
3) we need to get an imagery index that only covers the exact boundaries of the three state plane zones OR figure out how to only turn on the image layer for the zone your present county is in.  There is way too much overlap in the files that we have.

**Comment by shodge17** [comment]
I just loaded hi-res image grids that only overlap at the edges of the zones.

**Comment by shodge17** [comment]
Item 2 of my comments above can be ignored since #68 addresses how to not include layers not turned on.

**Comment by clintonlunn** [comment]
@shodge17  I just read your last comment. I will remove those changes.

**Comment by clintonlunn** [comment]
@shodge17, Georgianna just informed me that @brenardfreac is working on a solution to item 3 to eliminate the overlap within the hi-res imagery layers.

**Pull request closed without merging**
